---
title: "credit card"
output: html_document
date: "2023-10-08"
---

```{r setup, include=FALSE}
library(dplyr) 
library(caTools)    # for splitting data into training and test set
library(data.table)
library(ggplot2)    
library(corrplot)   
library(rpart)      
library(rpart.plot)
```

 
```{r credit card}
credit<- read.csv("c:/users/DELL/Downloads/creditcard.csv")
credit

```

 
```{r}
head(credit,10)
```


```{r}
summary(credit)
```


```{r}
hist(credit$Amount[credit$Amount<100])
```


```{r}
var(credit$Amount)
```


```{r}
sd(credit$Amount)
```


```{r Data Visualisation}
# visualizing the distribution of transcations across time
credit %>%
  ggplot(aes(x = Time, fill = factor(Class))) + 
  geom_histogram(bins = 100) + 
  labs(x = "Time elapsed since first transcation (seconds)", y = "no. of transactions", title = "Distribution of transactions across time") +
  facet_grid(Class ~ ., scales = 'free_y') + theme()
```


```{r}
# scaling the data using standardization and remove the first column (time) from the data set
credit$Amount <- scale(credit$Amount)
new_data <- credit[, -c(1)]
head(new_data)
```



```{r}
new_data$Class <- as.factor(new_data$Class)
levels(new_data$Class) <- c("Not Fraud", "Fraud")
```



```{r}
set.seed(101)
split <- sample.split(new_data$Class, SplitRatio = 0.8)
train_data <- subset(new_data, split == TRUE)
test_data <- subset(new_data, split == FALSE)
dim(train_data)
```



```{r}
logistic_model <- glm(Class ~ ., train_data, family='binomial')
```


```{r}
summary(logistic_model)
```


```{r}
plot(logistic_model)
```


```{r}
```


```{r}
```


```{r}
```









```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

 